ProjeCV/Controllers/HakkimdaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeCV.Models.Entity;
using ProjeCV.Models.Sınıf;

namespace ProjeCV.Controllers
{
    public class HakkimdaController : Controller
    {
        // GET: Hakkımda
        DbMvcCvEntities db = new DbMvcCvEntities();
        public ActionResult Index()
        {
            Class1 cs = new Class1();
            cs.Deger1 = db.TBLABOUT.ToList();
            return View(cs);
        }
        public ActionResult VeriGetir(int id)
        {
            var veriler = db.TBLABOUT.Find(id);
            return View("Veri Getir", veriler);
        }
        public ActionResult Guncelle(TBLABOUT p)
        {
            var degerler = db.TBLABOUT.Find(p.ID);
            degerler.NAME = p.NAME;
            degerler.SURNAME = p.SURNAME;
            degerler.PHONE = p.PHONE;
            degerler.MAİL = p.MAİL;
            degerler.ABOUT = p.ABOUT;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

ProjeCV/Views/Hakkimda/Index.cshtml
@model ProjeCV.Models.Sınıf.Class1
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>AD</th>
            <th>SOYAD</th>
            <th>ADRES</th>
            <th>TELEFON</th>
            <th>MAİL</th>
            <th>HAKKIMDA</th>
            <th>Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model.Deger1)
        {
        <tr>
            <th>@x.ID</th>
            <td>@x.NAME</td>
            <td>@x.SURNAME</td>
            <td>@x.ADDRESS</td>
            <td>@x.PHONE</td>
            <td>@x.MAİL</td>
            <td>@x.ABOUT</td>
            <td><a href="/Hakkımda/VeriGetir/@x.ID" class="btn btn-success">GÜNCELLE</a></td>

        </tr>
        }
    </tbody>
</table>

ProjeCV/Views/Hakkimda/VeriGetir.cshtml
@model ProjeCV.Models.Entity.TBLABOUT
@{
    ViewBag.Title = "VeriGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "Hakkimda", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.ID)
        @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })

        <br />

        @Html.Label("AD")
        @Html.TextBoxFor(x => x.NAME, new { @class = "form-control" })


        <br />

        @Html.Label("SOYAD")
        @Html.TextBoxFor(x => x.SURNAME, new { @class = "form-control" })


        <br />

        @Html.Label("TELEFON")
        @Html.TextBoxFor(x => x.PHONE, new { @class = "form-control" })
        <br />


        @Html.Label("MAİL")
        @Html.TextBoxFor(x => x.MAİL, new { @class = "form-control" })
        <br />

        @Html.Label("HAKKIMDA")
        @Html.TextAreaFor(x => x.ABOUT, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary">Güncelle</button>
    </div>

   

  

}