ProjeCV/Controllers/YeteneklerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeCV.Models.Entity;
using ProjeCV.Models.Sınıf;


namespace ProjeCV.Controllers
{
    public class YeteneklerController : Controller
    {
        // GET: Yetenekler
        DbMvcCvEntities db = new DbMvcCvEntities();
        public ActionResult Index()
        {
            Class1 cs = new Class1();
            cs.Deger4 = db.TBLSKILLS.ToList();
            return View(cs);
            
        }
        [HttpGet]
        public  ActionResult YeniYetenek()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniYetenek(TBLSKILLS p)
        {
            db.TBLSKILLS.Add(p);
            db.SaveChanges();
            return View(p);
        }
        public ActionResult Sil(int id)
        {
            var ytnk = db.TBLSKILLS.Find(id);
            db.TBLSKILLS.Remove(ytnk);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult YetenekGetir(int id)
        {
            var ytnk = db.TBLSKILLS.Find(id);
            return View("YetenekGetir", ytnk);
        }
        public ActionResult Guncelle(TBLSKILLS  p)
        {
            var degerler = db.TBLSKILLS.Find(p.ID);
            degerler.SKILL = p.SKILL;           
            return RedirectToAction("Index");
        }

    }
}

ProjeCV/Views/Yetenekler/Index.cshtml
@model ProjeCV.Models.Sınıf.Class1
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Yetenek</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>
            <th>ACTİONLİNK</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model.Deger4)
        {
        <tr>
            <th>@x.ID</th>
            <td>@x.SKILL</td>
            <td><a href="/Yetenekler/Sil/@x.ID" class="btn btn-danger">SİL</a></td>
            <td><a href="/Yetenekler/YeteneGetir/@x.ID" class="btn btn-success">GÜNCELLE</a></td>
            İstiyor Musun
            <td>@Html.ActionLink("Sil Butonu ", "Sil", new { id = x.ID },
               new { @class = "btn btn-warning", onclick = "return confirm ('Silmek İstiyor Musunuz?')" })</td>
        </tr>
        }
    </tbody>
</table>
<a href="/Yetenek/YetenekEkle" class="btn btn-info">Yeni Yetenek Ekle</a>        

ProjeCV/Views/Yetenekler/YeniYetenek.cshtml
@{
    ViewBag.Title = "YeniYetenek";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

    <form class="form-group" method="post">
        <div>
            <label>Yetenek </label>
            <input type="text" class="form-control" name="SKILL" />
        </div>
        <br />
        <button class="btn btn-primary">Kaydet</button>

    </form>

ProjeCV/Views/Yetenekler/YetenekGetir.cshtml
@model ProjeCV.Models.Entity.TBLSKILLS
@{
    ViewBag.Title = "YetenekGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using (@Html.BeginForm("Guncelle", "Yetenekler", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.ID)
        @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })
        <br />
        @Html.Label("Yetenek")
        @Html.TextBoxFor(x => x.SKILL, new { @class = "form-control" })
       
        <br />
        <button class="btn btn-primary">Güncelle</button>
    </div>