ProjeCV/Controllers/DeneyimlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeCV.Models.Entity;
using ProjeCV.Models.Sınıf;

namespace ProjeCV.Controllers
{
    public class DeneyimlerController : Controller
    {
        // GET: Deneyimler
        DbMvcCvEntities db = new DbMvcCvEntities();
        public ActionResult Index()
        {
            Class1 cs = new Class1();
            cs.Deger2 = db.TBLEXPERİENCE.ToList();
            return View(cs);
        }
        [HttpGet]
        public ActionResult YeniDeneyim()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult YeniDeneyim(TBLEXPERİENCE p)
        {
            db.TBLEXPERİENCE.Add(p);
            db.SaveChanges();
            return View();
        }
        public ActionResult DeneyimSil(int id)
        {
            var deneyim = db.TBLEXPERİENCE.Find(id);
            db.TBLEXPERİENCE.Remove(deneyim);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeneyimGetir(int id)
        {
            var veri = db.TBLEXPERİENCE.Find(id);
            return View("DeneyimGetir",veri);
        }
        public ActionResult Guncelle(TBLEXPERİENCE p)
        {
            var veriler = db.TBLEXPERİENCE.Find(p.ID);
            veriler.TİTLE = p.SUBTİTLE;
            veriler.SUBTİTLE = p.SUBTİTLE;
            veriler.DETAİLS = p.DETAİLS;
            veriler.DATE = p.DATE;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

ProjeCV/Views/Deneyimler/DeneyimGetir.cshtml
@model ProjeCV.Models.Entity.TBLEXPERİENCE
@{
    ViewBag.Title = "DeneyimGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (@Html.BeginForm("Guncelle","Deneyimler",FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.ID)
        @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })
        <br />
        @Html.Label("Deneyim Başlığı")
        @Html.TextBoxFor(x => x.TİTLE, new { @class = "form-control" })
        <br />
        @Html.Label("Deneyim Alt Başlığı")
        @Html.TextBoxFor(x => x.SUBTİTLE, new { @class = "form-control" })
        <br />
        @Html.Label("Tarih")
        @Html.TextBoxFor(x => x.DATE, new { @class = "form-control" })
        <br />
        @Html.Label("Detaylar")
        @Html.TextAreaFor(x => x.DETAİLS, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary">Güncelle</button>
    </div>
}

ProjeCV/Views/Deneyimler/Index.cshtml
@model ProjeCV.Models.Sınıf.Class1
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>BAŞLIK</th>
            <th>ALT BAŞLIK</th>
            <th>TARİH</th>
            <th>DETAYLAR</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>
            <th>ACTİONLİNK</th>


        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model.Deger2)
        {
        <tr>
            <th>@x.ID</th>
            <td>@x.TİTLE</td>
            <td>@x.SUBTİTLE</td>
            <td>@x.DATE</td>
            <td>@x.DETAİLS</td>
            <td><a href="/Deneyimler/DeneyimSil/@x.ID" class="btn btn-danger">SİL</a></td>
            <td><a href="/Deneyimler/DeneyimGetir/@x.ID" class="btn btn-success">GÜNCELLE</a></td>
            <td>
                @Html.ActionLink("Sil Butonu ", "Sil", new { id = x.ID },
          new { @class = "btn btn-warning", onclick = "return confirm ('Silmek İstiyor Musunuz?')" })
            </td>

        </tr>
        }
    </tbody>
</table>

<a href="/Deneyimler/YeniDeneyim/" class="btn btn-info">Yeni Deneyim Ekle</a>

ProjeCV/Views/Deneyimler/YeniDeneyim.cshtml
@{
    ViewBag.Title = "YeniDeneyim";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

    <form class="form-group" method="post">
        <div>
            <label>Deneyim Başlığı</label>
            <input type="text" class="form-control" name="TİTLE" />
        </div>
        <br />
        <div>
            <label>Deneyim Alt Başlığı</label>
            <input type="text" class="form-control" name="SUBTİTLE" />
        </div>
        <br />
        <div>
            <label>Tarih</label>
            <input type="text" class="form-control" name="DATE"/>
        </div>
        <br />
        <div>
            <label>Detaylar</label>
            <textarea class="form-control"rows="10" name="DETAİLS"></textarea>
        </div>
        <br />
        <button class="btn btn-primary" >Kaydet</button>

    </form>