ProjeCV/Controllers/KonferanslarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjeCV.Models.Entity;
using ProjeCV.Models.Sınıf;

namespace ProjeCV.Controllers
{
    public class KonferanslarController : Controller
    {
        // GET: Konferansnlar
        DbMvcCvEntities db = new DbMvcCvEntities();
        public ActionResult Index(string p)
        {
            var degerler = from d in db.TBLAWARDS select d;
            if (!string.IsNullOrEmpty(p) )
            {
                degerler = degerler.Where(m => m.AWARD.Contains(p));
            }
            //Class1 cs = new Class1();
            //cs.Deger6 = db.TBLAWARDS.ToList();
            return View(degerler.ToList());
        }
        [HttpGet]
        public ActionResult YeniKonferans()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniKonferans(TBLAWARDS p)
        {
            db.TBLAWARDS.Add(p);
            db.SaveChanges();
            return View(p);
        }
        public ActionResult Sil(int id)
        {
            var knfrns = db.TBLAWARDS.Find(id);
            db.TBLAWARDS.Remove(knfrns);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KonferansGetir(int id)
        {
            var veri = db.TBLAWARDS.Find(id);
            return View("KonferansGetir", veri);
        }
        public ActionResult Guncelle(TBLAWARDS p)
        {
            var veriler = db.TBLAWARDS.Find(p.ID);
            veriler.AWARD = p.AWARD;
            
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

ProjeCV/Views/Konferanslar/Index.cshtml
@using ProjeCV.Models.Entity
@model List<TBLAWARDS>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("Index", "Konferanslar", FormMethod.Get))
{
   <p>
       Aranacak Değer:@Html.TextBox("p")
       <input type="submit" value="Ara" />
   </p>
}


<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>KONFERANS</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>
            <th>ACTİONLİNK</th>
            //

        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
        <tr>
            <th>@x.ID</th>
            <td>@x.AWARD</td>
            <td><a href="/Konferanslar/Sil/@x.ID" class="btn btn-danger">SİL</a></td>
            <td><a href="/Konferanslar/KonferansGetir/@x.ID" class="btn btn-success">GÜNCELLE</a></td>
            <td>
                @Html.ActionLink("Sil Butonu ", "Sil", new { id = x.ID },
   new { @class = "btn btn-warning", onclick = "return confirm ('Silmek İstiyor Musunuz?')" })
            </td>


        </tr>
            }
    </tbody>

</table>
<a href="/Konferanslar/YeniKonferans/" class="btn btn-info">Yeni Konferans Ekle</a>

ProjeCV/Views/Konferanslar/KonferansGetir.cshtml
@model ProjeCV.Models.Entity.TBLAWARDS
@{
    ViewBag.Title = "KonferansGetir";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (@Html.BeginForm("Guncelle", "Konferanslar", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.ID)
        @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })
        <br />
        @Html.Label("Konferans")
        @Html.TextBoxFor(x => x.AWARD, new { @class = "form-control" })
        <br />
       
        <button class="btn btn-primary">Güncelle</button>
    </div>
}

ProjeCV/Views/Konferanslar/YeniKonferans.cshtml
@{
    ViewBag.Title = "YeniKonferans";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    <div>
        <label>Konferans</label>
        <input type="text" class="form-control" name="AWARD" />

    </div>
    <br />
    <button class="btn btn-primary">Kaydet</button>
</form>